Dynamic web forms with validation in java
Vaadin-en-Espanol/vaadin-en-espanol pull request #10
Opened 2019-12-31 14:43 UTC by cgnunezbantics

Sugiero nueva traducción. Gracias.

2020-01-02 13:45 UTC, alejandro-du requested changes
Gracias por el aporte. Dejé algunas observaciones. Continuaré con la revisión cuando estén solucionadas las observaciones actuales.

2020-01-02 13:45 UTC, alejandro-du commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +Al construir aplicaciones de negocios, el ingreso de datos es una de las tareas más comunes, es decir, formularios web vinculados a objetos de dominio o POJOs, validados a travez de complejas lógicas
"sobre REST"

2020-01-02 13:45 UTC, alejandro-du commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +En este ejemplo, construiremos un sistema de pedidos de snacks. El formulario requiere que el usuario ingrese su nombre y la cantidad de snacks. Usando un dropdown para seleccionar el tipo de snack,
La primera aparición de un término en Inglés debe ir en cursiva. Ejemplo, "snacks", "dropdown". Por favor, revisar el resto de documento y corregir.

2020-01-02 13:45 UTC, alejandro-du commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +Importá el projecto en un IDE de tú elección (ver intrucciones en https://vaadin.com/learn/tutorials/import-maven-project-intellij-idea[IntelliJ IDEA], https://vaadin.com/learn/tutorials/import-maven
Por favor, no usar Español rioplatence (importá->importa). Por favor, cambia otras ocurrencias de este tipo en el documento. Hay varias.

2020-01-02 15:47 UTC, cgnunezbantics commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +Al construir aplicaciones de negocios, el ingreso de datos es una de las tareas más comunes, es decir, formularios web vinculados a objetos de dominio o POJOs, validados a travez de complejas lógicas
Ok.

2020-01-02 15:47 UTC, cgnunezbantics commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +En este ejemplo, construiremos un sistema de pedidos de snacks. El formulario requiere que el usuario ingrese su nombre y la cantidad de snacks. Usando un dropdown para seleccionar el tipo de snack,
Ok.

2020-01-02 15:47 UTC, cgnunezbantics commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> +Importá el projecto en un IDE de tú elección (ver intrucciones en https://vaadin.com/learn/tutorials/import-maven-project-intellij-idea[IntelliJ IDEA], https://vaadin.com/learn/tutorials/import-maven
Ok.

2020-01-02 16:39 UTC, alejandro-du requested changes
Gracias por las correcciones, pero el problema persiste. Aún hay ocurrencias de Español rioplatense además de otras faltas ortográficas. Sugiero que pases el texto por un corrector ortográfico.

2020-02-12 09:35 UTC, alejandro-du approved these changes
Gracias!

2020-02-12 09:35 UTC, merged