Traducción de Vaadin quick start tutorial
Vaadin-en-Espanol/vaadin-en-espanol pull request #4
Opened 2019-11-13 20:00 UTC by cgnunezbantics

Traducción de Vaadin quick start tutorial

2019-11-13 22:09 UTC, alejandro-du requested changes
Gracias por el aporte! Dejé algunos comentarios de una revisión inicial. Espero puedas atenderlos. Saludos.

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> += Vaadin quick start tutorial
Requiere traducción

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Por favor eliminar meta tags no requeridas

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +En este tutorial, tú puedes aprender como contruir una aplicacion Vaadin pequeña, pero totalmente funcional. Este ejemplo te enseñará lo básico del desarrollo _component-based_ y _listening_ a _event
El pronombre "tú" es redundante

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +La aplicacion que tu contruirás es la aplicacion clásica _Todo_
Por favor, elimina el pronombre "tú" cuando sea redundante. Has lo mismo en el resto del documento.

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +image::app-overview.png[Aplicacion Todo con un _header_, _checkboxes_ para todo items y un _form_ para ingresar nuevos items]
El archivo con la imagen no está presente. Puedes copiarla del original y ponerla en la misma ubicación del archivo asciidoc. Revisar otras imágenes si es necesario y corregir.

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +En este tutorial, tú puedes aprender como contruir una aplicacion Vaadin pequeña, pero totalmente funcional. Este ejemplo te enseñará lo básico del desarrollo _component-based_ y _listening_ a _event
Cambiar a "desarrollo basado en componentes y manejo de eventos".

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Para continuar asegúrese de que al menos las siguientes herramientas estén instaladas:
Cambiar forma "usted" a "tú" (ejemplo: asegúrate). Lo mismo en el resto del documento.

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +== Baje un porjecto Vaadin minimo.
Cambiar "Baje" por "Descargando"
Typo en "proyecto".
"Mínimo" con tilde.

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que haya descargado el proyecto, descomprima el archivo, ej. a su directorio de _home_. Por ahora, no necesita instalar ningún IDE o servidor de aplicaciones. Utilizaremos un servidor simple
"_embedded_" -> "embebido".

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Vaadin es un _framework_ component-based. Construye interfaces de usuario creando instancias de componentes y colocándolos en layouts que determinan cómo se muestran. `MainView` extiende de `Vertical
"basado en componentes. Puedes construir..."

2019-11-13 22:09 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +<5> La llamada de `add` de VerticalLayout define cómo se deben mostrar los components. Observe que `taskField` y` addButton` están en un `HorizontalLayout`, que los coloca uno al lado del otro.
Error en formato de `addButton`

2019-11-15 12:19 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Corregido

2019-11-15 12:20 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> += Vaadin quick start tutorial
Corregido

2019-11-15 12:20 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +En este tutorial, tú puedes aprender como contruir una aplicacion Vaadin pequeña, pero totalmente funcional. Este ejemplo te enseñará lo básico del desarrollo _component-based_ y _listening_ a _event
Corregido

2019-11-15 12:20 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +image::app-overview.png[Aplicacion Todo con un _header_, _checkboxes_ para todo items y un _form_ para ingresar nuevos items]
Corregido

2019-11-15 12:27 UTC, cgnunezbantics commented
Buenos dias. Solicito nueva revision. Gracias.

2019-11-15 13:08 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +La aplicacion que tu contruirás es la aplicacion clásica _Todo_
Corregido

2019-11-15 13:21 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Para continuar asegúrese de que al menos las siguientes herramientas estén instaladas:
Corregido

2019-11-15 13:26 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +<5> La llamada de `add` de VerticalLayout define cómo se deben mostrar los components. Observe que `taskField` y` addButton` están en un `HorizontalLayout`, que los coloca uno al lado del otro.
Corregido

2019-11-15 13:27 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Vaadin es un _framework_ component-based. Construye interfaces de usuario creando instancias de componentes y colocándolos en layouts que determinan cómo se muestran. `MainView` extiende de `Vertical
Corregido

2019-11-15 13:27 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que haya descargado el proyecto, descomprima el archivo, ej. a su directorio de _home_. Por ahora, no necesita instalar ningún IDE o servidor de aplicaciones. Utilizaremos un servidor simple
Corregido

2019-11-15 13:29 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +== Baje un porjecto Vaadin minimo.
Corregido

2019-11-15 13:36 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Perdon, los tags se agreagan despues o dejo los que considero adecuados?

2019-11-15 13:43 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Los agregue corregido, por favor confirmar si corresponden o es otro procedimiento. Gracias.

2019-11-15 15:26 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Elimina todos los tags por favor

2019-11-15 15:42 UTC, alejandro-du requested changes
Gracias por hacer los cambios pronto. Dejo comentarios sobre una segunda iteración del artículo. Espero puedas resolverlos pronto también.

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:repo: https://github.com/cgnunezbantics/vaadin-en-espanol
Elimina esto por favor

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> += Construyendo un _web form_ dinámico con validación
Elimina este archivo para este PR. Usemos un PR por artículo

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +En este tutorial, podrás aprender como contruir una aplicacion Vaadin pequeña, pero totalmente funcional. Este ejemplo te enseñará lo básico del desarrollo _component-based_ y _listening_ a _events_.
Cambiar a "desarrollo basado en componentes y manejo de eventos".

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +La aplicacion que contruirás es la aplicacion clásica _Todo_
"Construirás la clásica aplicación _Todo_"

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que descargaste el proyecto, descomprí el archivo, por ej. en tu directorio de _home_. Por ahora, no necesitamos instalar ningún IDE o servidor de aplicaciones. Utilizararemos un servidor sim
Recomendaría hacer otra pasada por todo el artículo pues supongo inicialmente usaste Google Translator y algunas frases extraño. Por ejemplo "Una vez que descargarse el proyecto..." debería ser algo como "Una vez que hayas descargado el proyecto..." o "Una vez descargado el proyecto".

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que descargaste el proyecto, descomprí el archivo, por ej. en tu directorio de _home_. Por ahora, no necesitamos instalar ningún IDE o servidor de aplicaciones. Utilizararemos un servidor sim
Typo en "descomprí"

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Navegá a `http://localhost:8080[localhost:8080, rel="nofollow"]`, y deberás ver una aplicación Vaadin básica con un botón.
Error ortográfico en "Navegá" -> "Navega"

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Construí el proyecto y ejecutá la aplicación en un servidor Jetty embebido. En la carpeta raíz del proyecto, ejecutá el script `mvnw`.
Error ortográfico en "Construí" -> "Construye"

2019-11-15 15:42 UTC, alejandro-du commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Construí el proyecto y ejecutá la aplicación en un servidor Jetty embebido. En la carpeta raíz del proyecto, ejecutá el script `mvnw`.
Por favor revisar de nuevo todos los verbos conjugados con el estilo del Español _rioplatence_ en el artículo y cambiar a Español estándar.

2019-11-15 18:06 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:tags: Java, Flow, Spring, Spring Boot
Eliminados

2019-11-15 18:07 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +:repo: https://github.com/cgnunezbantics/vaadin-en-espanol
Echo

2019-11-15 18:10 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +En este tutorial, podrás aprender como contruir una aplicacion Vaadin pequeña, pero totalmente funcional. Este ejemplo te enseñará lo básico del desarrollo _component-based_ y _listening_ a _events_.
Corregido.

2019-11-15 18:16 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que descargaste el proyecto, descomprí el archivo, por ej. en tu directorio de _home_. Por ahora, no necesitamos instalar ningún IDE o servidor de aplicaciones. Utilizararemos un servidor sim
OK. Corregido. Realizare una repasada general. Te diria que esa frase, no estaria tan mal usada por aquí (BsAs Argentina, usamos mucho el que, che, aca.), pero las que sugeris son totalmente correctas.

2019-11-15 18:17 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +La aplicacion que contruirás es la aplicacion clásica _Todo_
Corregido

2019-11-15 18:17 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Una vez que descargaste el proyecto, descomprí el archivo, por ej. en tu directorio de _home_. Por ahora, no necesitamos instalar ningún IDE o servidor de aplicaciones. Utilizararemos un servidor sim
ok

2019-11-15 18:18 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Construí el proyecto y ejecutá la aplicación en un servidor Jetty embebido. En la carpeta raíz del proyecto, ejecutá el script `mvnw`.
Jaja ok.

2019-11-15 18:59 UTC, cgnunezbantics commented on tutoriales/vaadin-quick-start/contenido.adoc
> +Construí el proyecto y ejecutá la aplicación en un servidor Jetty embebido. En la carpeta raíz del proyecto, ejecutá el script `mvnw`.
Creo que quedo todo bien.

2019-11-15 19:05 UTC, cgnunezbantics reviewed
Corregido

2019-11-15 19:05 UTC, cgnunezbantics commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> += Construyendo un _web form_ dinámico con validación
OK

2019-11-15 19:05 UTC, cgnunezbantics commented on tutoriales/dynamic-web-forms-with-validation-in-java/contenido.adoc
> += Construyendo un _web form_ dinámico con validación
Corregido.

2019-11-19 09:23 UTC, alejandro-du reviewed
lgtm

2019-11-19 09:23 UTC, merged