#3 Traducir Calling Java from JavaScript
Vaadin-en-Espanol/vaadin-en-espanol pull request #6
Opened 2019-11-18 03:45 UTC by dfcortes

* Agregado archivo .adoc conteniendo el texto de la traduccion a Español.
* Agregada imagenes de ayuda que son usadas en el archivo .adoc.

2019-11-19 10:11 UTC, alejandro-du requested changes
Gracias por el aporte! Agregué algunas observaciones que sería genial si puedes resolver pronto.

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Usualmente las aplicaciones Java del lado del servidor pueden habilitar métodos para ser expuestos como un _end-point_ usando Servicios Web REST.  Aunque este es un enfoque completamente correcto, es
Por favor elimina la palabra "Flow" (Vaadin Flow -> Vaadin).

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +En este tutorial paso a paso aprenderás a usar Vaadin para llamar código Java del lado del servidor desde código JavaScript del lado del cliente. Lo único que necesitas para seguir el tutorial es ent
Cambiar a "Lenguaje de Programación Java"
Cambar "Java IDE" por "IDE Java"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: Puedes encontrar el código fuente del tutorial original en Inglés en https://github.com/vaadin-learning-center/calling-java-from-javascript[GitHub].
Cambiar a "[...] el codigo fuente del tutorial en [...]"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # Configurando el proyecto
Eliminar caracter "#"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Ir a esta https://vaadin.com/start/latest/project-base[página].
"Ir" -> "Ve a https://vaadin[...]"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Da clic en el botón *Download* y debes extraer el contenido del archivo ZIP que fue generado.
"Da click en el botón *Download" y extrae el [...]"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: No te inquietes si no conoces Maven. La mayoría de IDEs tienen un soporte excelente para Maven y no necesitas entender todos sus detalles para usarlo. Si quieres aprender más acerca de concepto
"No te preocupes si [...]"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # Creando una página web vacía
Eliminar "#"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Las aplicaciones web Java son implementadas a través de Servlets. Un Servlet es una clase que mejora la funcionalidad de un servidor web (los cuales usualmente alojan archivos tales como HTML, docume
"... es una clase que agrega funcionalidad a un servidor web...."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Las aplicaciones web Java son implementadas a través de Servlets. Un Servlet es una clase que mejora la funcionalidad de un servidor web (los cuales usualmente alojan archivos tales como HTML, docume
"Esta funcionalidad podría incluir..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Las aplicaciones web Java son implementadas a través de Servlets. Un Servlet es una clase que mejora la funcionalidad de un servidor web (los cuales usualmente alojan archivos tales como HTML, docume
Eliminar artículo "tú" redundante ("Cuando _tú_ incluyes..." -> "Cuando incluyes....").

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Para ver como crea una nueva clase con el nombre de `VistaPrincipal` en el paquete `com.ejemplo`:
"Para ver esto en acción, crea una nueva clase..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Queremos exponer esta clase como una página web, como tenemos a Vaadin in nuestro proyecto y este crea un `VaadinServlet` lo único que necesitamos hacer es agregar una anotación a la clase creada pre
"Vaadin en nuestro proyecto"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Queremos exponer esta clase como una página web, como tenemos a Vaadin in nuestro proyecto y este crea un `VaadinServlet` lo único que necesitamos hacer es agregar una anotación a la clase creada pre
"...hacer es anotar la clase creada previamente..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Queremos exponer esta clase como una página web, como tenemos a Vaadin in nuestro proyecto y este crea un `VaadinServlet` lo único que necesitamos hacer es agregar una anotación a la clase creada pre
"y hacer que la clase extienda..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Por defecto, la anotación `@Route` permite a Vaadin mapear la clase con la raíz del contexto cuando la clase anotada se denomina `VistaPrincipal`. Por lo tanto, cuando se lanza la petición a `http://
"mapear la clase a..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Si ejecutas el proyecto en este punto, obtendrás una página web vacía. Confirmémoslo ejecutando el Plugin Maven de Jetty. Si tienes Maven instalado en tu máquina, solo ejecuta la instrucción `mvn jet
"línea de comandos"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # Llamando JavaScript.
Eliminar #

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Antes de llamar JavaScript desde Java, necesitamos configurar el archivo JavaScript en sí. Crear un nuevo archivo con el nombre `script.js` en el directorio `frontend` y escribe una función en él:
"Crea un archivo..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Prueba la aplicación ahora. Detener el servidor y reinícialo (usando la configuración de ejecución en tu IDE o escribiendo la instrucción `mvn jetty:run`  usando la línea de comando).
"linea de comandos"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # Llamando Java
Eliminar #

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora que esta funcionando la invocación de JavaScript desde Java, vamos a completar el circulo invocando un método Java desde una función JavaScript. Primero, necesitamos implementar un método Java.
"Implementemos un saludo en Java del lado del servidor..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora, necesitamos exponer este método al lado del cliente anotando el método con `@ClientCallable`:
"... anotándolo con ..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Para llamar este método desde el lado del cliente, necesitamos retornar la referencia del método Java `getElement()`. Podemos enviarlo hacia la función JavaScript modificando el constructor de la cla
"... necesitamos la referencia que el método Java `getElement()` retorna."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Puede notar que agregamos el argumento (`$1`) al llamado del a función y ahora añadimos el valor actual como un argumento extra en el llamado hacia el método `executeJs`.
"Observa como agregamos.... al llamado de la función y como pasamos ese valor en un argumento extra en la llamada al método..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora podemos aceptar este valor al JavaScript del lado del cliente, agregando un parámetro a la función `saludar` de la siguiente manera:
"... este valor en JavaScript..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +El objecto `elemento` incluye un miembro `$server` que podemos usar para llamar el método `saludar` Java desde el lado del servidor, Aquí esta como se hace:
"El objeto..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +El objecto `elemento` incluye un miembro `$server` que podemos usar para llamar el método `saludar` Java desde el lado del servidor, Aquí esta como se hace:
"el método Java `saludar` del lado del servidor"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Reinicie el servidor Jetty de nuevo y consulta la aplicación para ver el saludo en el log del servidor:
"Reinicia...."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Reinicie el servidor Jetty de nuevo y consulta la aplicación para ver el saludo en el log del servidor:
"... e invoca la aplicación..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # ¿Qué sigue?
Eliminar #

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Cerramos el circulo de llamar JavaScript desde Java y Java desde JavaScript sin usar Servicios Web REST. Si completaste este tutorial, posiblemente ya tienes ideas sobre qué probar a continuación. Po
"Y así, el círculo está completo. Hemos llamado JavaScript desde..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Cerramos el circulo de llamar JavaScript desde Java y Java desde JavaScript sin usar Servicios Web REST. Si completaste este tutorial, posiblemente ya tienes ideas sobre qué probar a continuación. Po
"agregar algo de CSS..."

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +No obstante, Vaadin es mucho más que una librería para conectar JavaScript con Java. Como te puedes imaginar, el mecanismo de comunicación automatizado de Vaadin puede ser usado para generar potentes
"la clase `VistaPrincipal` de la siguiente forma:"

2019-11-19 10:11 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Sin escribir código en JavaScript en absoluto, tú obtienes una aplicación web basada en HTML en el navegador.
Eliminar "tú" redundante

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Usualmente las aplicaciones Java del lado del servidor pueden habilitar métodos para ser expuestos como un _end-point_ usando Servicios Web REST.  Aunque este es un enfoque completamente correcto, es
Done

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +En este tutorial paso a paso aprenderás a usar Vaadin para llamar código Java del lado del servidor desde código JavaScript del lado del cliente. Lo único que necesitas para seguir el tutorial es ent
Done

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: Puedes encontrar el código fuente del tutorial original en Inglés en https://github.com/vaadin-learning-center/calling-java-from-javascript[GitHub].
Done

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # Configurando el proyecto
Done

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Ir a esta https://vaadin.com/start/latest/project-base[página].
Done

2019-11-21 19:43 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +== # ¿Qué sigue?
Done

2019-11-21 19:44 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Cerramos el circulo de llamar JavaScript desde Java y Java desde JavaScript sin usar Servicios Web REST. Si completaste este tutorial, posiblemente ya tienes ideas sobre qué probar a continuación. Po
Done

2019-11-21 19:44 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Cerramos el circulo de llamar JavaScript desde Java y Java desde JavaScript sin usar Servicios Web REST. Si completaste este tutorial, posiblemente ya tienes ideas sobre qué probar a continuación. Po
Done

2019-11-21 19:44 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +No obstante, Vaadin es mucho más que una librería para conectar JavaScript con Java. Como te puedes imaginar, el mecanismo de comunicación automatizado de Vaadin puede ser usado para generar potentes
Done

2019-11-21 19:44 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Sin escribir código en JavaScript en absoluto, tú obtienes una aplicación web basada en HTML en el navegador.
Done

2019-11-21 19:46 UTC, dfcortes commented
@alejandro-du El PR se encuentra actualizado con los cambios sugeridos.

2019-11-22 11:32 UTC, alejandro-du requested changes
Gracias por los cambios. Agregué comentarios para una seguda iteración del artículo. Espero puedas solucionarlos pronto.

2019-11-22 11:32 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: Puedes encontrar el código fuente del tutorial original en Inglés en https://github.com/vaadin-learning-center/calling-java-from-javascript[...]
Falta el texto del link

2019-11-22 11:32 UTC, alejandro-du commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Ve a https://vaadin.com/start/latest/project-base[...]
Falta el texto del link. Cuando puse [...] lo hice para referenciar texto que habías escrito. Por favor revisar que no hay otras incidencias de esto y corregir si es necesario.

2019-11-22 16:27 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: Puedes encontrar el código fuente del tutorial original en Inglés en https://github.com/vaadin-learning-center/calling-java-from-javascript[...]
Done

2019-11-22 16:30 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Ve a https://vaadin.com/start/latest/project-base[...]
Me confundí aplicando esas sugerencias, ya el PR esta actualizado agregando el texto en los links, el documento no tiene incidencias similares.

2019-11-27 13:17 UTC, alejandro-du requested changes
Parece que aún faltan algunos comentarios por solucionar (veo "#" en los títulos por ejemplo). Por favor revisar, corregir y solicitar una nueva revisión. Saludos.

2019-12-09 11:33 UTC, alejandro-du requested changes
@dfcortes, algún chance de hacer las correcciones pendientes pronto?

2019-12-09 16:52 UTC, dfcortes commented
@alejandro-du perdón por tardar en resolver las sugerencias de cambio. Ya quedaron resultas los cambios referentes al "#".  Estoy atento si se requieren otras modificaciones.

2019-12-10 08:43 UTC, alejandro-du requested changes
Hola @dfcortes, gracias por las modificaciones, pero aún hay varios comentarios sin resolver: https://github.com/Vaadin-en-Espanol/vaadin-en-espanol/pull/6/files

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +. Da clic en el botón *Download* y debes extraer el contenido del archivo ZIP que fue generado.
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +NOTE: No te inquietes si no conoces Maven. La mayoría de IDEs tienen un soporte excelente para Maven y no necesitas entender todos sus detalles para usarlo. Si quieres aprender más acerca de concepto
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Las aplicaciones web Java son implementadas a través de Servlets. Un Servlet es una clase que mejora la funcionalidad de un servidor web (los cuales usualmente alojan archivos tales como HTML, docume
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Para ver como crea una nueva clase con el nombre de `VistaPrincipal` en el paquete `com.ejemplo`:
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Queremos exponer esta clase como una página web, como tenemos a Vaadin in nuestro proyecto y este crea un `VaadinServlet` lo único que necesitamos hacer es agregar una anotación a la clase creada pre
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Por defecto, la anotación `@Route` permite a Vaadin mapear la clase con la raíz del contexto cuando la clase anotada se denomina `VistaPrincipal`. Por lo tanto, cuando se lanza la petición a `http://
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Si ejecutas el proyecto en este punto, obtendrás una página web vacía. Confirmémoslo ejecutando el Plugin Maven de Jetty. Si tienes Maven instalado en tu máquina, solo ejecuta la instrucción `mvn jet
Done

2019-12-10 11:25 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Antes de llamar JavaScript desde Java, necesitamos configurar el archivo JavaScript en sí. Crear un nuevo archivo con el nombre `script.js` en el directorio `frontend` y escribe una función en él:
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Prueba la aplicación ahora. Detener el servidor y reinícialo (usando la configuración de ejecución en tu IDE o escribiendo la instrucción `mvn jetty:run`  usando la línea de comando).
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora que esta funcionando la invocación de JavaScript desde Java, vamos a completar el circulo invocando un método Java desde una función JavaScript. Primero, necesitamos implementar un método Java.
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora, necesitamos exponer este método al lado del cliente anotando el método con `@ClientCallable`:
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Para llamar este método desde el lado del cliente, necesitamos retornar la referencia del método Java `getElement()`. Podemos enviarlo hacia la función JavaScript modificando el constructor de la cla
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Puede notar que agregamos el argumento (`$1`) al llamado del a función y ahora añadimos el valor actual como un argumento extra en el llamado hacia el método `executeJs`.
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Ahora podemos aceptar este valor al JavaScript del lado del cliente, agregando un parámetro a la función `saludar` de la siguiente manera:
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +El objecto `elemento` incluye un miembro `$server` que podemos usar para llamar el método `saludar` Java desde el lado del servidor, Aquí esta como se hace:
Done

2019-12-10 11:26 UTC, dfcortes commented on tutoriales/llamar-java-desde-javaScript/contenido.adoc
> +Reinicie el servidor Jetty de nuevo y consulta la aplicación para ver el saludo en el log del servidor:
Done

2019-12-10 11:28 UTC, batouxclass reviewed
@alejandro-du  los comentarios pendientes fueron atendidos, el PR fue actualizado con ellos.

2019-12-10 15:16 UTC, alejandro-du approved these changes
Good job. Thanks!

2019-12-10 15:16 UTC, merged