Traducir tutorial getting-started-with-flow a español
Vaadin-en-Espanol/vaadin-en-espanol pull request #8
Opened 2019-12-06 16:01 UTC by Geovanny0401

Traducir tutorial getting-started-with-flow a español 
- Creando carpetas
- Creando archivo contenido.adoc

2019-12-09 11:36 UTC, alejandro-du requested changes
No hay contenido. El archivo está vacío. Has el PR cuando el documento esté listo.

2019-12-16 14:35 UTC, alejandro-du requested changes
Gracias por el aporte. Por favor revisa el comentario que dejé.

2019-12-16 14:35 UTC, alejandro-du commented on tutoriales/getting-started-with-flow/contenido.adoc
> +Todo lo que necesitas son conocimientos básicos de programación, un link:https://en.wikipedia.org/wiki/Integrated_development_environment[IDE] como link:https://en.wikipedia.org/wiki/IntelliJ_IDEA[In
Usemos la forma "tu" en ves de "usted", tal como se menciona en https://github.com/Vaadin-en-Espanol/vaadin-en-espanol. Este párrafo contiene las dos formas y veo otras partes del documento incorrectas también. Por favor revisar todo el documento y corregir todas las posibles ocurrencias. Una vez corregido esto, continuaré con la revisión. Gracias.

2019-12-18 15:52 UTC, alejandro-du requested changes
No has corregido el problema con el idioma. Por favor lee todo el documento, identifica los problemas con el idioma y corrígelos. Adicionalmente evita usar la variante costeña del idioma Español. Ejemplo, cambia "Tú va a construir" por "Tú vas a construir". De nuevo, revisa esto en todo el documento. Sugiero que lo leas antes de hacer un nuevo commit. Una vez corregido la totalidad del documento, puedo continuar con la revisión. Gracias.

2019-12-18 15:52 UTC, alejandro-du commented on tutoriales/getting-started-with-flow/contenido.adoc
> +Todo lo que necesitas son conocimientos básicos de programación, un link:https://en.wikipedia.org/wiki/Integrated_development_environment[IDE] como link:https://en.wikipedia.org/wiki/IntelliJ_IDEA[In
"bold italic"???

2019-12-18 15:52 UTC, alejandro-du commented on tutoriales/getting-started-with-flow/contenido.adoc
> +Todo lo que necesitas son conocimientos básicos de programación, un link:https://en.wikipedia.org/wiki/Integrated_development_environment[IDE] como link:https://en.wikipedia.org/wiki/IntelliJ_IDEA[In
Cambiar a "... IntelliJ IDEA, JDK versión 8 o posterior, ..."

2019-12-18 15:52 UTC, alejandro-du commented on tutoriales/getting-started-with-flow/contenido.adoc
> +Todo lo que necesitas son conocimientos básicos de programación, un link:https://en.wikipedia.org/wiki/Integrated_development_environment[IDE] como link:https://en.wikipedia.org/wiki/IntelliJ_IDEA[In
Aún veo el mismo problema con el idioma: Por favor, usa "tú" en ves de "usted". No debe ser "dependiendo de **su** experiencia" sino "dependiendo de *tu* experiencia. Corrige esto en todo el documento, por favor.

2020-02-12 09:31 UTC, alejandro-du commented
Hola, aún sigues trabajando en esta traducción?

2020-02-12 14:13 UTC, Geovanny0401 commented
Hola @alejandro-du si claro, esperando si tiene alguna observación o si esta OK para mirar si realizo otra traducion de otro tutorial de vaadin.

2020-02-12 14:24 UTC, alejandro-du commented
Aún no veo corregidos los problemas.

2023-04-14 05:41 UTC, closed without merging